/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmaciasaplicacion;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author pogbom
 */
public class administracion extends java.awt.Dialog {

    public modelo model = new modelo();
    public conexion con = new conexion();
    public Object[][] dtFarm;
    public Object[][] dtMed;
    public Object[][] dtCd;
    public Object[][] dtTra;
    public Object[][] dtPresen;
    DefaultTableModel datosFarm;
    DefaultTableModel datosMed;
    DefaultTableModel datosPresen;
    DefaultTableModel datosTra;

    /**
     * Creates new form administracion
     */
    public administracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private void updateTablaFarmacia() {
        String[] columNames = {"Nombre", "Direccion", "Telefono", "Ciudad"};
        // se utiliza la funcion
        dtFarm = model.getFarmacias();

        // se colocan los datos en la tabla
        datosFarm = new DefaultTableModel(dtFarm, columNames);
        jTable3.setModel(datosFarm);
        //jScrollPane1.getViewport().add(jTable3);

    }

    private void updateTablaMedicamentos() {
        String[] columNames = {"Nombre", "Prospecto", "Laboratorio"};
        // se utiliza la funcion
        dtMed = model.getMedicamentos();

        // se colocan los datos en la tabla
        datosMed = new DefaultTableModel(dtMed, columNames);
        jTable4.setModel(datosMed);
        //jScrollPane2.getViewport().add(jTable4);
    }

    private void updateTablaPresentaciones() {
        String[] columNames = {"Nombre", "Presentacion", "Stock", "Precio"};
        // se utiliza la funcion
        dtPresen = model.getDatosPresentacion();

        // se colocan los datos en la tabla
        datosPresen = new DefaultTableModel(dtPresen, columNames);
        jTable1.setModel(datosPresen);
        //jScrollPane3.getViewport().add(jTable1);
    }

    private void updateTablaTrabajadores() {
        String[] columNames = {"Usuario", "DNI" , "Contraseña", "Nombre", "Telefono"};
        // se utiliza la funcion
        dtTra = model.getTrabajadores();

        // se colocan los datos en la tabla
        datosTra = new DefaultTableModel(dtTra, columNames);
        jTable6.setModel(datosTra);
        //jScrollPane4.getViewport().add(jTable6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        panel1 = new org.edisoncor.gui.panel.Panel();
        tabbedPaneHeader1 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panel3 = new org.edisoncor.gui.panel.Panel();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric8 = new org.edisoncor.gui.label.LabelMetric();
        txtNomFarmacia = new org.edisoncor.gui.textField.TextField();
        txtDirFarmacia = new org.edisoncor.gui.textField.TextField();
        txtTelFarmacia = new org.edisoncor.gui.textField.TextField();
        btnReg1 = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        cmboxFarmacia = new javax.swing.JComboBox();
        panel5 = new org.edisoncor.gui.panel.Panel();
        labelMetric9 = new org.edisoncor.gui.label.LabelMetric();
        txtNomMedicamento = new org.edisoncor.gui.textField.TextField();
        labelMetric10 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric11 = new org.edisoncor.gui.label.LabelMetric();
        txtProsMedicamento = new org.edisoncor.gui.textField.TextField();
        btnReg2 = new javax.swing.JButton();
        btnModMedicamentos = new javax.swing.JButton();
        btnEliMedicamentos = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        cmbBoxMedicamentos = new javax.swing.JComboBox();
        panel2 = new org.edisoncor.gui.panel.Panel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric5 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric6 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        txtNomCd = new org.edisoncor.gui.textField.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRegPresentaciones = new javax.swing.JButton();
        btnEliCd = new javax.swing.JButton();
        btnModCd = new javax.swing.JButton();
        jComboBox1Presentacionas = new javax.swing.JComboBox();
        spinnerCiudades = new javax.swing.JSpinner();
        spinnerprecio = new javax.swing.JSpinner();
        panel4 = new org.edisoncor.gui.panel.Panel();
        labelMetric12 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric13 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric14 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric15 = new org.edisoncor.gui.label.LabelMetric();
        txtContTra = new org.edisoncor.gui.textField.TextField();
        txtNomTra = new org.edisoncor.gui.textField.TextField();
        txtTelTra = new org.edisoncor.gui.textField.TextField();
        btnReg4 = new javax.swing.JButton();
        btnMod4 = new javax.swing.JButton();
        btnEli4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        labelMetric16 = new org.edisoncor.gui.label.LabelMetric();
        txtDniTrabajador = new org.edisoncor.gui.textField.TextField();
        comboUsuTra = new javax.swing.JComboBox();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panel1.setColorSecundario(new java.awt.Color(0, 0, 204));

        panel3.setColorSecundario(new java.awt.Color(0, 0, 204));

        labelMetric2.setText("Nombre");
        labelMetric2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric3.setText("Direccion");
        labelMetric3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric4.setText("Telefono");
        labelMetric4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric8.setText("Ciudad");
        labelMetric8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txtNomFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomFarmaciaActionPerformed(evt);
            }
        });

        txtDirFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirFarmaciaActionPerformed(evt);
            }
        });

        txtTelFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelFarmaciaActionPerformed(evt);
            }
        });

        btnReg1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnReg1.setForeground(new java.awt.Color(255, 255, 255));
        btnReg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo-icono-5812-48.png"))); // NOI18N
        btnReg1.setText("Registrar");
        btnReg1.setBorder(null);
        btnReg1.setContentAreaFilled(false);
        btnReg1.setDefaultCapable(false);
        btnReg1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReg1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReg1ActionPerformed(evt);
            }
        });

        btnModificar1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnModificar1.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt-icono-7208-48.png"))); // NOI18N
        btnModificar1.setText("Modificar");
        btnModificar1.setBorder(null);
        btnModificar1.setBorderPainted(false);
        btnModificar1.setContentAreaFilled(false);
        btnModificar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tar-icono-9842-48.png"))); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.setBorder(null);
        btnEliminar1.setContentAreaFilled(false);
        btnEliminar1.setDefaultCapable(false);
        btnEliminar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Telefono", "Ciudad"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        cmboxFarmacia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cmboxFarmacia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tampico", "Cd Madero", "Guadalajara", "Monterrey", "Teziutlan" }));
        cmboxFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxFarmaciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDirFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(cmboxFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(263, Short.MAX_VALUE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(btnReg1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmboxFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReg1)
                    .addComponent(btnModificar1)
                    .addComponent(btnEliminar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        tabbedPaneHeader1.addTab("Farmacias", panel3);

        panel5.setColorSecundario(new java.awt.Color(0, 0, 204));

        labelMetric9.setText("Nombre");
        labelMetric9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric10.setText("Prospecto");
        labelMetric10.setToolTipText("");
        labelMetric10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric11.setText("Laboratorio");
        labelMetric11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txtProsMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProsMedicamentoActionPerformed(evt);
            }
        });

        btnReg2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnReg2.setForeground(new java.awt.Color(255, 255, 255));
        btnReg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo-icono-5812-48.png"))); // NOI18N
        btnReg2.setText("Registrar");
        btnReg2.setBorder(null);
        btnReg2.setBorderPainted(false);
        btnReg2.setContentAreaFilled(false);
        btnReg2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReg2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReg2ActionPerformed(evt);
            }
        });

        btnModMedicamentos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnModMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnModMedicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt-icono-7208-48.png"))); // NOI18N
        btnModMedicamentos.setText("Modificar");
        btnModMedicamentos.setBorder(null);
        btnModMedicamentos.setBorderPainted(false);
        btnModMedicamentos.setContentAreaFilled(false);
        btnModMedicamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModMedicamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModMedicamentosActionPerformed(evt);
            }
        });

        btnEliMedicamentos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEliMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnEliMedicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tar-icono-9842-48.png"))); // NOI18N
        btnEliMedicamentos.setText("Eliminar");
        btnEliMedicamentos.setBorder(null);
        btnEliMedicamentos.setBorderPainted(false);
        btnEliMedicamentos.setContentAreaFilled(false);
        btnEliMedicamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliMedicamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliMedicamentosActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Prospecto", "Laboratorio"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        cmbBoxMedicamentos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cmbBoxMedicamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laboratorio central", "Laboratorio norte", "Laboratorio sur" }));

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnReg2)
                        .addGap(85, 85, 85)
                        .addComponent(btnModMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btnEliMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetric11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProsMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtNomMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(cmbBoxMedicamentos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(57, 127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProsMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReg2)
                    .addComponent(btnModMedicamentos)
                    .addComponent(btnEliMedicamentos))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabbedPaneHeader1.addTab("Medicamentos", panel5);

        panel2.setColorSecundario(new java.awt.Color(0, 0, 204));

        labelMetric1.setText("Nombre");
        labelMetric1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric5.setText("Presentacion");
        labelMetric5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric6.setText("Stock");
        labelMetric6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric7.setText("Precio");
        labelMetric7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Presentacion", "Stock", "Precio"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnRegPresentaciones.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnRegPresentaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnRegPresentaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo-icono-5812-48.png"))); // NOI18N
        btnRegPresentaciones.setText("Registrar");
        btnRegPresentaciones.setBorder(null);
        btnRegPresentaciones.setBorderPainted(false);
        btnRegPresentaciones.setContentAreaFilled(false);
        btnRegPresentaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegPresentaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegPresentaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegPresentacionesActionPerformed(evt);
            }
        });

        btnEliCd.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEliCd.setForeground(new java.awt.Color(255, 255, 255));
        btnEliCd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tar-icono-9842-48.png"))); // NOI18N
        btnEliCd.setText("Eliminar");
        btnEliCd.setBorder(null);
        btnEliCd.setBorderPainted(false);
        btnEliCd.setContentAreaFilled(false);
        btnEliCd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliCd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliCd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliCdActionPerformed(evt);
            }
        });

        btnModCd.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnModCd.setForeground(new java.awt.Color(255, 255, 255));
        btnModCd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt-icono-7208-48.png"))); // NOI18N
        btnModCd.setText("Modificar");
        btnModCd.setBorder(null);
        btnModCd.setBorderPainted(false);
        btnModCd.setContentAreaFilled(false);
        btnModCd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModCd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModCd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCdActionPerformed(evt);
            }
        });

        jComboBox1Presentacionas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jComboBox1Presentacionas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comprimidos", "Tabletas", "Ampolletas", "Jarabe", "Pomada" }));

        spinnerCiudades.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        spinnerCiudades.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        spinnerprecio.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        spinnerprecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegPresentaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnModCd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnEliCd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1Presentacionas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomCd, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerprecio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinnerCiudades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomCd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1Presentacionas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModCd)
                    .addComponent(btnRegPresentaciones)
                    .addComponent(btnEliCd))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneHeader1.addTab("Inventario", panel2);

        panel4.setColorSecundario(new java.awt.Color(0, 0, 204));

        labelMetric12.setText("Usuario");
        labelMetric12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric13.setText("Contraseña");
        labelMetric13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric14.setText("Nombre");
        labelMetric14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        labelMetric15.setText("Telefono");
        labelMetric15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        btnReg4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnReg4.setForeground(new java.awt.Color(255, 255, 255));
        btnReg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo-icono-5812-48.png"))); // NOI18N
        btnReg4.setText("Registrar");
        btnReg4.setBorder(null);
        btnReg4.setBorderPainted(false);
        btnReg4.setContentAreaFilled(false);
        btnReg4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReg4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReg4ActionPerformed(evt);
            }
        });

        btnMod4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnMod4.setForeground(new java.awt.Color(255, 255, 255));
        btnMod4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt-icono-7208-48.png"))); // NOI18N
        btnMod4.setText("Modificar");
        btnMod4.setBorder(null);
        btnMod4.setBorderPainted(false);
        btnMod4.setContentAreaFilled(false);
        btnMod4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMod4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMod4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMod4ActionPerformed(evt);
            }
        });

        btnEli4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEli4.setForeground(new java.awt.Color(255, 255, 255));
        btnEli4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tar-icono-9842-48.png"))); // NOI18N
        btnEli4.setText("Eliminar");
        btnEli4.setBorder(null);
        btnEli4.setBorderPainted(false);
        btnEli4.setContentAreaFilled(false);
        btnEli4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEli4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEli4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEli4ActionPerformed(evt);
            }
        });

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Usuario", "DNI", "Contraseña", "Nombre", "Telefono"
            }
        ));
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable6);

        labelMetric16.setText("Dni Trabajador");

        comboUsuTra.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        comboUsuTra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "farmaceutico", "trabajador", "administrador" }));

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetric15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnReg4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelMetric14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomTra, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(txtTelTra, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(txtContTra, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(txtDniTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboUsuTra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(btnMod4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                .addComponent(btnEli4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetric16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUsuTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReg4)
                    .addComponent(btnMod4)
                    .addComponent(btnEli4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPaneHeader1.addTab("Trabajadores", panel4);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        updateTablaFarmacia();
        updateTablaMedicamentos();
        updateTablaPresentaciones();
        updateTablaTrabajadores();
    }//GEN-LAST:event_closeDialog

    private void txtNomFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomFarmaciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomFarmaciaActionPerformed

    private void txtDirFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirFarmaciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirFarmaciaActionPerformed

    private void txtTelFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelFarmaciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelFarmaciaActionPerformed

    private void btnReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReg1ActionPerformed
        // TODO add your handling code here:
        String nomFarmReg = txtNomFarmacia.getText();
        String dirFarmReg = txtDirFarmacia.getText();
        String telFarmReg = txtTelFarmacia.getText();
        String cdFarmReg = cmboxFarmacia.getSelectedItem().toString();
        model.insertarFarmacia(nomFarmReg, dirFarmReg, telFarmReg, cdFarmReg);
        updateTablaFarmacia();
    }//GEN-LAST:event_btnReg1ActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        // TODO add your handling code here:
        String nomFarmMod = txtNomFarmacia.getText();
        String dirFarmMod = txtDirFarmacia.getText();
        String telFarmMod = txtTelFarmacia.getText();
        //String cdFarmMod = txtCdFarmacia.getText();
        String cdFarmMod = cmboxFarmacia.getSelectedItem().toString();
        model.ModificarFarmacias(nomFarmMod, dirFarmMod, telFarmMod, cdFarmMod);
        updateTablaFarmacia();
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        String resultEliFarm = datosFarm.getValueAt(
                jTable3.getSelectedRow(), 0).toString();
        model.EliminarFarmacia(resultEliFarm);
        updateTablaFarmacia();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnReg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReg2ActionPerformed
        // TODO add your handling code here:
        String nomMedReg = txtNomMedicamento.getText();
        String prosMedReg = txtProsMedicamento.getText();
        //String labMedReg = txtLabMedicamento.getText();
        String labMedReg = cmbBoxMedicamentos.getSelectedItem().toString();
        model.insertarMedicamento(nomMedReg, prosMedReg, labMedReg);
        updateTablaMedicamentos();
    }//GEN-LAST:event_btnReg2ActionPerformed

    private void btnModMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModMedicamentosActionPerformed
        // TODO add your handling code here:
        String nomMedMod = txtNomMedicamento.getText();
        String prosMedMod = txtProsMedicamento.getText();
        //String labMedMod = txtLabMedicamento.getText();
        String labMedMod = cmbBoxMedicamentos.getSelectedItem().toString();
        model.ModificarMedicamentos(nomMedMod, prosMedMod, labMedMod);
        updateTablaMedicamentos();
    }//GEN-LAST:event_btnModMedicamentosActionPerformed

    private void btnEliMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliMedicamentosActionPerformed
        // TODO add your handling code here:
        String resultEliMed = datosMed.getValueAt(
                jTable4.getSelectedRow(), 0).toString();
        model.EliminarMedicamentos(resultEliMed);
        updateTablaMedicamentos();
    }//GEN-LAST:event_btnEliMedicamentosActionPerformed

    private void btnReg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReg4ActionPerformed
        // TODO add your handling code here:
        String usuRegTra = comboUsuTra.getSelectedItem().toString();
        String dniRegTra = txtDniTrabajador.getText();
        String contraRegTra = txtContTra.getText();
        String nomRegTra = txtNomTra.getText();
        String telRegTra = txtTelTra.getText();
        model.insertarTrabajadores(usuRegTra,dniRegTra, contraRegTra, nomRegTra, telRegTra);
        updateTablaTrabajadores();
    }//GEN-LAST:event_btnReg4ActionPerformed

    private void btnMod4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMod4ActionPerformed
        // TODO add your handling code here:
        String usuModTra = comboUsuTra.getSelectedItem().toString();
        String dniModTra = txtDniTrabajador.getText();
        String contraModTra = txtContTra.getText();
        String nomModTra = txtNomTra.getText();
        String telModTra = txtTelTra.getText();
        model.ModificarTrabajadores(usuModTra,dniModTra , contraModTra, nomModTra, telModTra);
        updateTablaTrabajadores();
    }//GEN-LAST:event_btnMod4ActionPerformed

    private void btnEli4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEli4ActionPerformed
        // TODO add your handling code here:
        String resultEliTrabajaores = datosTra.getValueAt(
                jTable6.getSelectedRow(), 0).toString();
        model.EliminarTrabajadores(resultEliTrabajaores);
        updateTablaTrabajadores();
    }//GEN-LAST:event_btnEli4ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        String nomTabla3 = datosFarm.getValueAt(
                jTable3.getSelectedRow(), 0).toString();
        String dirTabla3 = datosFarm.getValueAt(
                jTable3.getSelectedRow(), 1).toString();
        String telTabla3 = datosFarm.getValueAt(
                jTable3.getSelectedRow(), 2).toString();
        //String cdTabla3 = datosFarm.getValueAt(
               // jTable3.getSelectedRow(), 3).toString();
        txtNomFarmacia.setText(nomTabla3); 
        txtDirFarmacia.setText(dirTabla3);
        txtTelFarmacia.setText(telTabla3); 
       // cmboxFarmacia.setText(cdTabla3);
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        String nomTabla4 = datosMed.getValueAt(
                jTable4.getSelectedRow(),0).toString();
        String prosTabla4 = datosMed.getValueAt(
                jTable4.getSelectedRow(),1).toString();
        //String labTabla4 = datosMed.getValueAt(
               // jTable4.getSelectedRow(),2).toString();
        txtNomMedicamento.setText(nomTabla4);
        txtProsMedicamento.setText(prosTabla4);
        //txtLabMedicamento.setText(labTabla4);
    }//GEN-LAST:event_jTable4MouseClicked

    private void jTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseClicked
        // TODO add your handling code here:
       String usuTabla6 = datosTra.getValueAt(
                jTable6.getSelectedRow(),0).toString();
        String dniTabla6= datosTra.getValueAt(
                jTable6.getSelectedRow(),1).toString();
        String contraTabla6 = datosTra.getValueAt(
                jTable6.getSelectedRow(),2).toString();
        String nomTabla6 = datosTra.getValueAt(
                jTable6.getSelectedRow(),3).toString();
        String telTabla6 = datosTra.getValueAt(
                jTable6.getSelectedRow(),4).toString();
        
      comboUsuTra.setToolTipText(usuTabla6);
      txtDniTrabajador.setText(dniTabla6);
      txtContTra.setText(contraTabla6);
      txtNomTra.setText(nomTabla6);
      txtTelTra.setText(telTabla6);
    }//GEN-LAST:event_jTable6MouseClicked

    private void btnRegPresentacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegPresentacionesActionPerformed
        // TODO add your handling code here:
        String nomPreReg = txtNomCd.getText();
        String prePreReg = jComboBox1Presentacionas.getSelectedItem().toString();
        //String DniFCdReg = txtDniCd.getText();
        String cantidadReg =spinnerCiudades.getValue().toString();
        //String AnoTCdReg = txtAnoCd.getText();
        String precioReg = spinnerprecio.getValue().toString();
        model.insertarPresentaciones(nomPreReg, prePreReg, cantidadReg,precioReg);
        updateTablaPresentaciones();
    }//GEN-LAST:event_btnRegPresentacionesActionPerformed

    private void btnModCdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCdActionPerformed
        // TODO add your handling code here:
        String nomModCd = txtNomCd.getText();
        String preModCd = jComboBox1Presentacionas.getSelectedItem().toString();
        String stockModCd = spinnerCiudades.getValue().toString();
        String precioMod = spinnerprecio.getValue().toString();
        model.ModificarPresentaciones(nomModCd,preModCd , stockModCd, precioMod);
        updateTablaPresentaciones();
    }//GEN-LAST:event_btnModCdActionPerformed

    private void btnEliCdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliCdActionPerformed
        // TODO add your handling code here:
        String resultEliPresentaciones = datosPresen.getValueAt(
                jTable1.getSelectedRow(), 0).toString();
        model.EliminarPresentaciones(resultEliPresentaciones);
        updateTablaPresentaciones();
    }//GEN-LAST:event_btnEliCdActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String nomTabla1 = datosPresen.getValueAt(
                jTable1.getSelectedRow(),0).toString();
        String provTabla1= datosPresen.getValueAt(
                jTable1.getSelectedRow(),1).toString();
        String StockTabla1 = datosPresen.getValueAt(
                jTable1.getSelectedRow(),2).toString();
         String precioTabla1 = datosPresen.getValueAt(
                jTable1.getSelectedRow(),3).toString();
        /*String DniTTabla1 = datosCd.getValueAt(
                jTable1.getSelectedRow(),2).toString();
        String AnoTTabla1 = datosCd.getValueAt(
                jTable1.getSelectedRow(),3).toString();*/
     txtNomCd.setText(nomTabla1);
     jComboBox1Presentacionas.setToolTipText(provTabla1);
     spinnerCiudades.setToolTipText(StockTabla1);
     spinnerprecio.setToolTipText(precioTabla1);
     // txtDniCd.setText(DniTTabla1);
      //txtAnoCd.setText(AnoTTabla1);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtProsMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProsMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProsMedicamentoActionPerformed

    private void cmboxFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxFarmaciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboxFarmaciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                administracion dialog = new administracion(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEli4;
    private javax.swing.JButton btnEliCd;
    public javax.swing.JButton btnEliMedicamentos;
    public javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnMod4;
    private javax.swing.JButton btnModCd;
    public javax.swing.JButton btnModMedicamentos;
    public javax.swing.JButton btnModificar1;
    public javax.swing.JButton btnReg1;
    public javax.swing.JButton btnReg2;
    private javax.swing.JButton btnReg4;
    private javax.swing.JButton btnRegPresentaciones;
    public static javax.swing.JComboBox cmbBoxMedicamentos;
    public static javax.swing.JComboBox cmboxFarmacia;
    private javax.swing.JComboBox comboUsuTra;
    public static javax.swing.JComboBox jComboBox1Presentacionas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric10;
    private org.edisoncor.gui.label.LabelMetric labelMetric11;
    private org.edisoncor.gui.label.LabelMetric labelMetric12;
    private org.edisoncor.gui.label.LabelMetric labelMetric13;
    private org.edisoncor.gui.label.LabelMetric labelMetric14;
    private org.edisoncor.gui.label.LabelMetric labelMetric15;
    private org.edisoncor.gui.label.LabelMetric labelMetric16;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.label.LabelMetric labelMetric5;
    private org.edisoncor.gui.label.LabelMetric labelMetric6;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private org.edisoncor.gui.label.LabelMetric labelMetric8;
    private org.edisoncor.gui.label.LabelMetric labelMetric9;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.Panel panel5;
    private javax.swing.JSpinner spinnerCiudades;
    private javax.swing.JSpinner spinnerprecio;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader1;
    private org.edisoncor.gui.textField.TextField txtContTra;
    private org.edisoncor.gui.textField.TextField txtDirFarmacia;
    private org.edisoncor.gui.textField.TextField txtDniTrabajador;
    private org.edisoncor.gui.textField.TextField txtNomCd;
    private org.edisoncor.gui.textField.TextField txtNomFarmacia;
    private org.edisoncor.gui.textField.TextField txtNomMedicamento;
    private org.edisoncor.gui.textField.TextField txtNomTra;
    private org.edisoncor.gui.textField.TextField txtProsMedicamento;
    private org.edisoncor.gui.textField.TextField txtTelFarmacia;
    private org.edisoncor.gui.textField.TextField txtTelTra;
    // End of variables declaration//GEN-END:variables
}
