/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmaciasaplicacion;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pogbom
 */
public class Buscador extends java.awt.Dialog {

   public conexion con = new conexion();
   ResultSet rsBuscador;
    /**
     * Creates new form farmacias
     */
    public Buscador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        btnBuscarTrabajadores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBuscador = new javax.swing.JTable();
        btnBuscarMedicamentos = new javax.swing.JButton();
        btnBuscarFarmacias = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panel1.setColorSecundario(new java.awt.Color(0, 0, 204));

        btnBuscarTrabajadores.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnBuscarTrabajadores.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/todo-icono-4868-48.png"))); // NOI18N
        btnBuscarTrabajadores.setText("Trabajadores");
        btnBuscarTrabajadores.setBorder(null);
        btnBuscarTrabajadores.setBorderPainted(false);
        btnBuscarTrabajadores.setContentAreaFilled(false);
        btnBuscarTrabajadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarTrabajadores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTrabajadoresActionPerformed(evt);
            }
        });

        TablaBuscador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(TablaBuscador);

        btnBuscarMedicamentos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnBuscarMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarMedicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/viruskiller-icono-4145-48.png"))); // NOI18N
        btnBuscarMedicamentos.setText("Medicamentos");
        btnBuscarMedicamentos.setBorder(null);
        btnBuscarMedicamentos.setBorderPainted(false);
        btnBuscarMedicamentos.setContentAreaFilled(false);
        btnBuscarMedicamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarMedicamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMedicamentosActionPerformed(evt);
            }
        });

        btnBuscarFarmacias.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnBuscarFarmacias.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarFarmacias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monitor-icono-8544-48.png"))); // NOI18N
        btnBuscarFarmacias.setText("Farmacias");
        btnBuscarFarmacias.setBorder(null);
        btnBuscarFarmacias.setBorderPainted(false);
        btnBuscarFarmacias.setContentAreaFilled(false);
        btnBuscarFarmacias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarFarmacias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarFarmacias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFarmaciasActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Buscar Dni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton2.setText("Buscar Nombre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton3.setText("Buscar Nombre");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(btnBuscarTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnBuscarMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jButton2)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnBuscarFarmacias, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarMedicamentos)
                    .addComponent(btnBuscarTrabajadores)
                    .addComponent(btnBuscarFarmacias))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        add(panel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnBuscarTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTrabajadoresActionPerformed
        // TODO add your handling code here:
        try{
        DefaultTableModel modeloBuscar;
       con= new conexion(); 
       String SQL = "select usuario,dni,nombre,telefono from Trabajadores";
       modeloBuscar = con.retornarDatos(SQL);
       TablaBuscador.setModel(modeloBuscar);
       jScrollPane1.getViewport().add(TablaBuscador);
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarTrabajadoresActionPerformed

    private void btnBuscarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicamentosActionPerformed
        // TODO add your handling code here:
        try{
        DefaultTableModel modeloBuscar;
       con= new conexion(); 
       String SQL = "select nombre as medicamento,prospecto,nombrelaboratorio as laboratorio"
               + ",nombrepresentacion as presentacion, cantidadstock as Stock,precio"
               + " from Medicamentos,Datos_Presentacion where nombre=nombremedicamento";
       modeloBuscar = con.retornarDatos(SQL);
       TablaBuscador.setModel(modeloBuscar);
       jScrollPane1.getViewport().add(TablaBuscador);
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarMedicamentosActionPerformed

    private void btnBuscarFarmaciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFarmaciasActionPerformed
        // TODO add your handling code here:
        try{
        DefaultTableModel modeloBuscar;
       con= new conexion(); 
       String SQL = "select Farmacias.nombre as Farmacia,direccion,telefono,"
               + "Ciudades.nombre as Ciudad,provincia from Farmacias"
               + " inner join Ciudades on Farmacias.nombreciudad = Ciudades.nombre";
       modeloBuscar = con.retornarDatos(SQL);
       TablaBuscador.setModel(modeloBuscar);
       jScrollPane1.getViewport().add(TablaBuscador);
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarFarmaciasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
        DefaultTableModel modeloBuscar;
       con= new conexion(); 
       String dniBuscar = "";
       dniBuscar=JOptionPane.showInputDialog("Ingrese el dni del Trabajador");
       rsBuscador= con.consulta("select dni from Trabajadores");
       boolean encontrado = false;
       while(rsBuscador.next()){
           if (dniBuscar.equals(rsBuscador.getObject("dni"))) {
               encontrado =true;
               break;
           }
       }
       String SQL = "select usuario,dni,nombre,telefono from Trabajadores where dni='"+dniBuscar+"'";
       modeloBuscar = con.retornarDatos(SQL);
       TablaBuscador.setModel(modeloBuscar);
       jScrollPane1.getViewport().add(TablaBuscador);
            if (encontrado==false) {
                JOptionPane.showMessageDialog(null, "No se encontro ningun registro con el Dni "+dniBuscar);
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        DefaultTableModel modeloBuscar;
       con= new conexion(); 
       String nombreBuscar = "";
       nombreBuscar=JOptionPane.showInputDialog("Ingrese el nombre del Medicamento");
       rsBuscador= con.consulta("select nombremedicamento from Datos_presentacion");
       boolean encontrado = false;
       while(rsBuscador.next()){
           if (nombreBuscar.equals(rsBuscador.getObject("nombremedicamento"))) {
               encontrado =true;
               break;
           }
       }
       String SQL = "select nombremedicamento as Medicamento,nombrepresentacion as"
               + " Presentacion, cantidadstock as Almacen, precio from Datos_presentacion "
               + " where Datos_presentacion.nombremedicamento='"+nombreBuscar+"'";
       modeloBuscar = con.retornarDatos(SQL);
       TablaBuscador.setModel(modeloBuscar);
       jScrollPane1.getViewport().add(TablaBuscador);
            if (encontrado==false) {
                JOptionPane.showMessageDialog(null, "No se encontro el medicamento "+nombreBuscar);
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        DefaultTableModel modeloBuscar;
       con= new conexion(); 
       String nombreBuscar = "";
       nombreBuscar=JOptionPane.showInputDialog("Ingrese el nombre de la Farmacia");
       rsBuscador= con.consulta("select nombre from Farmacias");
       boolean encontrado = false;
       while(rsBuscador.next()){
           if (nombreBuscar.equals(rsBuscador.getObject("nombre"))) {
               encontrado =true;
               break;
           }
       }
       String SQL = "select Farmacias.nombre as Farmacia,direccion,telefono,Ciudades.nombre as Ciudad,provincia from Farmacias inner join Ciudades on Farmacias.nombreciudad = Ciudades.nombre where Farmacias.nombre='"+nombreBuscar+"'";
       modeloBuscar = con.retornarDatos(SQL);
       TablaBuscador.setModel(modeloBuscar);
       jScrollPane1.getViewport().add(TablaBuscador);
            if (encontrado==false) {
                JOptionPane.showMessageDialog(null, "No se encontro la farmacia "+nombreBuscar);
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Buscador dialog = new Buscador(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaBuscador;
    public javax.swing.JButton btnBuscarFarmacias;
    public javax.swing.JButton btnBuscarMedicamentos;
    public javax.swing.JButton btnBuscarTrabajadores;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
