/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmaciasaplicacion;

/**
 *
 * @author pogbom
 */
public class logueo extends java.awt.Dialog {

    /**
     * Creates new form logueo
     */
    public logueo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        txtPassword = new org.edisoncor.gui.passwordField.PasswordField();
        txtUsuario = new org.edisoncor.gui.textField.TextField();
        botonsesionAceptar = new org.edisoncor.gui.button.ButtonAero();
        btnlimpiarlogin = new org.edisoncor.gui.button.ButtonAero();

        setLocationRelativeTo(panel1);
        setMinimumSize(new java.awt.Dimension(350, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panel1.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMetric1.setText("Usuario");
        labelMetric1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        panel1.add(labelMetric1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        labelMetric2.setText("Contraseña");
        labelMetric2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        panel1.add(labelMetric2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        panel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, -1));

        botonsesionAceptar.setText("Aceptar");
        botonsesionAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsesionAceptarActionPerformed(evt);
            }
        });
        panel1.add(botonsesionAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        btnlimpiarlogin.setText("Borrar");
        btnlimpiarlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarloginActionPerformed(evt);
            }
        });
        panel1.add(btnlimpiarlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 90, -1));

        add(panel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void botonsesionAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsesionAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonsesionAceptarActionPerformed

    private void btnlimpiarloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarloginActionPerformed
        // TODO add your handling code here:
        txtUsuario.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnlimpiarloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                logueo dialog = new logueo(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.edisoncor.gui.button.ButtonAero botonsesionAceptar;
    private org.edisoncor.gui.button.ButtonAero btnlimpiarlogin;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.panel.Panel panel1;
    public org.edisoncor.gui.passwordField.PasswordField txtPassword;
    public org.edisoncor.gui.textField.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
